version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: {  interval: "daily" }
    labels: [ "area:deps", "area:ci" ]
    reviewers: [ "rdeago" ]
  - package-ecosystem: "nuget"
    directory: "/SampleProject"
    schedule: {  interval: "daily" }
    labels: [ "area:deps" ]
    reviewers: [ "rdeago" ]
